### ISSUE TITLE
Define a way to let controllers "late initialize" spec fields

### ISSUE THREAD

**Issue by muvaf** [crossplaneio/crossplane-runtime#10]
### What problem are you facing?

While it's general consensus that the controller should not manipulate `spec`, i.e. desired state, in some cases the developer might want to update `spec` to adopt late initialization pattern that exists in Kubernetes https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#late-initialization

One could argue that defaulting via admission webhook could solve this, however, for external resources some fields are only available after the creation of the resource.

### How could Crossplane help solve your problem?

There should be a way that allows spec update but I don't think all update calls we make should be converted from status. update. We need to define a way that implies that only in some cases, developer should opt for whole resource update, otherwise keep updating only status.

**Comment by negz** [comment]
> We need to define a way that implies that only in some cases, developer should opt for whole resource update, otherwise keep updating only status.

Sadly I don't believe this is possible for resources that use the status subresource; calling `client.Update()` updates only the object metadata and spec, and calling `client.Status().Update()` updates only the status.

**Comment by negz** [comment]
Cross referencing https://github.com/crossplaneio/crossplane/issues/290, since I believe these issues are somewhat related.

It should be possible to do this today without any changes to the managed resource reconciler by plumbing the `client.Client` (i.e. Kubernetes client) through from the `resource.ExternalConnector` (which already has it) to the `resource.ExternalClient` that it produces. The `Observe` method of any `resource.ExternalClient` that requires late initialisation would be responsible for updating the spec of the managed resource under reconciliation, calling `client.Update()`, and handling any error.

**Comment by negz** [comment]
An example of the pattern I suggested in https://github.com/crossplaneio/crossplane-runtime/issues/10#issuecomment-528239162 - late initialising the spec inside the `Observe` call - exists in the global address controller added in https://github.com/crossplaneio/crossplane/pull/750 .

**Comment by muvaf** [comment]
> The Observe method of any resource.ExternalClient that requires late initialisation would be responsible for updating the spec of the managed resource under reconciliation, calling client.Update(), and handling any error.

Hoped we can come up with a generic way to do it but I guess deferring it to `Observe` is as good as we can get since dealing with resource's configuration parameters in a generic way is usually not worth the headache.
